ChrisMarekPhotography/Models/HeaderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChrisMarekPhotography.Models
{
    public class HeaderViewModel
    {
        public IPhotosResult photosResult { get; set; }
    }
}

ChrisMarekPhotography/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataLibrary;
using ChrisMarekPhotography.Models;
using static DataLibrary.BusinessLogic.CustomerProcessor;


namespace ChrisMarekPhotography.Controllers
{
    public class AjaxController : ControllerBase
    {
        public AjaxController()
        { }


        /// <summary>
        /// Redirect that remains on the same page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ToogleCaching()
        {
            SetCache();
            ActionResult result = Redirect(HttpContext.Request.UrlReferrer.AbsolutePath);
            return result;
        }


        [ChildActionOnly]
        public ActionResult RenderHeader()
        {
            IPhotosResult validatedPhotosResult = GetFacade().GetValidationResults();
            var model = new HeaderViewModel()
            {
                photosResult = validatedPhotosResult
            };
            return PartialView("partial/_Header", model);
        }

        [ChildActionOnly]
        public ActionResult RenderSignUp()
        {
            Models.CustomerModel cust = new Models.CustomerModel();
            return PartialView("partial/_SignUp", cust);
        }


        /// <summary>
        /// This is the Portfolio View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet, NoCache, LogActionFilter]
        public ActionResult GetPortfolioImages(string folder)
        {
            var watch = System.Diagnostics.Stopwatch.StartNew();
            IPhotoViewModel photoViewModel = GetFacade().GetImages(folder);
            watch.Stop();
            var elapsedMs = watch.ElapsedMilliseconds;

            return PartialView("partial/_Image", photoViewModel);
        }

        /// <summary>
        /// This is the SlideShow that is the very first page to be displayed at start up.
        /// </summary>
        /// <param name="folder"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet, NoCache, LogActionFilter]
        public ActionResult GetSlideShowImages(string folder)
        {
            IPhotoViewModel photoViewModel = GetFacade().GetImages(folder);
            return PartialView("partial/_SlideShowImage", photoViewModel);
        }


        /// <summary>
        /// This is the Images that are requested from the drop-down selection on the Images view
        /// </summary>
        /// <param name="folder"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet, NoCache, LogActionFilter]
        public ActionResult SearchImages(string folder)
        {
            IPhotoViewModel photoViewModel = GetFacade().GetImages(folder);
            return PartialView("partial/_Image", photoViewModel);
        }
    }
}

ChrisMarekPhotography/Views/Shared/Partial/_Header.cshtml
@using ChrisMarekPhotography;
@using ChrisMarekPhotography.Models
@model HeaderViewModel



<div class="container center">
    <div class="banner" align="center">
        <img class="imageDescription" src="~/Images/HomeBanner.png" alt="chris marek photography" width="850" height="100" />
    </div>
    <div class="row">
        <div class="photography-nav slideshow-link">
            @Html.ActionLink("Home", "Home", "Home")
        </div>
        <div class="photography-nav portfolio-link">
            @Html.ActionLink("Portfolio", "Index", "Home")
        </div>
        <div class="photography-nav images-link">
            @Html.ActionLink("Images", "Images", "Home")
        </div>
        <div class="photography-nav about-link">
            @Html.ActionLink("About", "About", "Home")
        </div>
        <div class="photography-nav">
            @Html.ActionLink("Contact", "Contact", "Home")
        </div>
    </div>
</div>

<div>
    <a href="@Url.Action("ToogleCaching", "Ajax")" title="Click to toggle between Caching On/Off">@(((bool)System.Web.HttpContext.Current.Session[ChrisMarekPhotography.Controllers.ControllerBase.SessionKeys.ApplicationCacheKey]) ? "On" : "Off")</a>
</div>
@if (Model.photosResult.HasErrors)
{
    <table align="center" id="errors list">
        <tbody>
            <tr class="validation-message">
                <td>Some errors have been found in the 'photos' folders</td>
            </tr>
            <tr class="validation-message">
                <td>----------------------------------------------------</td>
            </tr>
            @foreach (string errors in Model.photosResult.ErrorMessages)
            {
                <tr class="validation-message">
                    <td>@errors</td>
                </tr>
            }
        </tbody>
    </table>
}

ChrisMarekPhotography/Views/Shared/Partial/_Image.cshtml
@using ChrisMarekPhotography;
@using ChrisMarekPhotography.Models;
@model PhotoViewModel

@foreach (IPhotoInformation info in Model.PhotoInformation)
{
    <li data-property="@info.Index" class="column portfolio imageDescription @info.Type @info.SpecificType">
        <a href="#">
            <img src="@Url.Content(@info.ImagePath)" alt="Image" class="portfolioImage" />
        </a>
        <div style="width: 100px" class="breakword overlay">@info.ImageDescription (@info.Index)</div>
    </li>
}

ChrisMarekPhotography/Views/Shared/Partial/_SignUp.cshtml
@using ChrisMarekPhotography.Models;
@model CustomerModel


<div align="center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        //by putting the term 'container' into the class, now the partial view will align to center finally!!!
        <div class="form-horizontal container  row">
            <fieldset class="customLegend1">
                <legend>NEWSLETTER SIGN-UP:</legend>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    <div class="col-md-1"></div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-1"></div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-1"></div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-1"></div>
                    <div class="col-md-1">
                        @Html.LabelFor(model => model.ConfirmEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ConfirmEmail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmEmail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <input type="submit" value="Submit" class="btn btn-default" id="register" />
                    </div>
                </div>
            </fieldset>
            <div>
                <fieldset class="customLegend2">
                    <legend>UpComing Events:</legend>
                    <table>
                        <tbody>
                            <tr>
                                <td class="eventmessages">Birding at White Rock Lake</td>
                            </tr>
                            <tr>
                                <td class="eventmessages">Birding at University Southwest medical center rookery</td>
                            </tr>
                            <tr>
                                <td class="eventmessages">Birding at Village creek drying beds</td>
                            </tr>
                            <tr>
                                <td class="eventmessages">Birding at Bosque del Apache in New Mexico</td>
                            </tr>
                            <tr>
                                <td class="eventmessages">Native Texas wildflowers</td>
                            </tr>
                        </tbody>
                    </table>

                </fieldset>
            </div>
        </div>
    }
</div>

ChrisMarekPhotography/Views/Shared/Partial/_SlideShowImage.cshtml
@using ChrisMarekPhotography;
@using ChrisMarekPhotography.Models;
@model PhotoViewModel

@foreach (IPhotoInformation info in Model.PhotoInformation)
{
    //Put this back in if you want photo description on mouse over
    @*<li class="imageDescription">
            <img src="@Url.Content(@info.ImagePath)" alt="Image" class="ssimage" style="display: none">
            <div class="overlay">@info.ImageDescription</div>
        </li>*@

    <li class="slideshow center">
        <img src="@Url.Content(@info.ImagePath)" alt="Image" class="ssimage" >
    </li>
}

ChrisMarekPhotography/Views/Shared/Partial/_UrlMap.cshtml
<script type="text/javascript">
    // should map directly to Controller.Action
    var urlMap = {
        Ajax: {
            GetPortfolioImages: "@Url.Action("GetPortfolioImages", "Ajax")",
            SearchImages: "@Url.Action("SearchImages", "Ajax")",
            GetSlideShowImages: "@Url.Action("GetSlideShowImages", "Ajax")"
        },
        Home: {

        }
    };
</script>